//! Two-layer transport conformance (transport spec §8): what the APPLICATION sent
//! versus what the SERVER observed, measured by two instruments that never infer one
//! from the other.
//!
//! The central claim under test is the spec's reason to exist: **equal application
//! requests do not imply equal transport wires**. One canonical request is driven
//! through the built-in ureq/rustls stack and through an operator-selected delegate;
//! the application observations must be identical and the transport observations
//! must differ. Each transport's own identity is then pinned against a committed
//! capture, so a dependency bump that changes what upstreams see is a reviewable
//! fixture diff rather than a silent change.
//!
//! Unix-only: the delegate is a spawned program and the failure-path stubs are
//! shell scripts (`transport_failures.rs`).
#![cfg(unix)]

#[allow(dead_code)]
#[path = "live_support/exec.rs"]
mod exec;
mod transport_support;

use transport_support::temp::{self, TempPath};
use transport_support::tls::fingerprint;
use transport_support::HttpObserver;

/// The response every observation run replays — a complete anthropic stream, so the
/// run exits 0 and the comparison is of a SUCCESSFUL round-trip.
const BASIC: &str = include_str!("fixtures/anthropic_messages_basic.sse");

/// The headers Brazen itself puts on the `WireRequest` — the application layer. Any
/// other header in the observed head was generated by the transport stack.
const BRAZEN_HEADERS: &[&str] = &["x-api-key", "content-type", "anthropic-version"];

/// A provider row pointed at `base_url`, optionally delegating its HTTP to
/// `program`. Written to a temp file the caller passes as `--config`.
fn config(base_url: &str, program: Option<&str>) -> TempPath {
    let delegate = program.map_or_else(String::new, |p| {
        format!("\n  [provider.transport]\n  program = \"{p}\"\n")
    });
    temp::config(&format!(
        r#"
[[provider]]
name = "obs"
base_url = "{base_url}"
protocol = "anthropic_messages"
auth = "api_key"
api_header = {{ name = "x-api-key", scheme = "raw" }}
beta_headers = [["anthropic-version", "2023-06-01"]]
body_defaults = {{ max_tokens = 16 }}
{delegate}"#
    ))
}

/// The delegate under test: `examples/stdio_transport`, the spec's own reference
/// implementation (§8.3). Plain `cargo test` builds examples next to the binaries,
/// so that copy is used when present; a coverage run works in its own target dir
/// where nothing builds examples, so the harness compiles it once into a scratch dir
/// instead. Either way a REAL program performs the HTTP — never a stub of one.
fn delegate_program() -> String {
    static PATH: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    PATH.get_or_init(|| {
        let bz = std::path::PathBuf::from(env!("CARGO_BIN_EXE_bz"));
        let sibling = bz
            .parent()
            .expect("bin dir")
            .join("examples")
            .join("stdio_transport");
        if sibling.is_file() {
            return sibling.to_string_lossy().into_owned();
        }
        let scratch = std::env::temp_dir().join("bz_transport_example");
        let built = std::process::Command::new(env!("CARGO"))
            .args(["build", "--example", "stdio_transport", "--target-dir"])
            .arg(&scratch)
            .current_dir(env!("CARGO_MANIFEST_DIR"))
            .status()
            .expect("build the delegate example");
        assert!(built.success(), "building examples/stdio_transport failed");
        scratch
            .join("debug/examples/stdio_transport")
            .to_string_lossy()
            .into_owned()
    })
    .clone()
}

/// Drive the real `bz` at `observer` (through `program`, when given) and hand back
/// the exit code and what the server saw.
fn observe(
    observer: &HttpObserver,
    program: Option<&str>,
) -> (i32, transport_support::HttpObservation) {
    let cfg = config(&observer.base_url(), program);
    let args: Vec<String> = [
        "--config",
        cfg.to_str().expect("config path"),
        "--provider",
        "obs",
        "--model",
        "claude-x",
        "--api-key",
        "sk-observed",
        "hi",
    ]
    .iter()
    .map(|s| (*s).to_owned())
    .collect();
    let (code, _, stderr) = exec::run_bz(&args, "");
    assert_eq!(code, 0, "bz failed: {stderr}");
    (code, observer.observed())
}

#[test]
fn equal_application_requests_do_not_imply_equal_transport_wires() {
    // THE claim (spec §2.2). Same canonical request, two transports.
    let built_in = HttpObserver::start(200, "", BASIC);
    let (_, a) = observe(&built_in, None);
    let delegated = HttpObserver::start(200, "", BASIC);
    let (_, b) = observe(&delegated, Some(&delegate_program()));

    // Application layer: identical. The delegate changed nothing the request means.
    assert_eq!(
        a.application(BRAZEN_HEADERS),
        b.application(BRAZEN_HEADERS),
        "the delegate must not alter the application request"
    );
    // Transport layer: different. Generated headers, their casing and order, and the
    // framing are the stack's, not the request's — which is the whole point.
    assert_ne!(
        a.transport(built_in.port),
        b.transport(delegated.port),
        "two stacks produced byte-identical wires; the layers would not be separable"
    );
    // And the difference is real, not incidental whitespace: only one of them is
    // the ureq build, so only one announces itself.
    assert!(a.head.to_lowercase().contains("user-agent"));
    assert!(!b.head.to_lowercase().contains("user-agent"));
}

#[test]
fn the_built_in_transport_matches_its_committed_capture() {
    // Pin what upstreams observe from the shipped stack: a ureq/rustls bump that
    // changes generated headers, casing, order or framing shows up as a fixture diff.
    let observer = HttpObserver::start(200, "", BASIC);
    let (_, seen) = observe(&observer, None);
    assert_capture("builtin_http_head.txt", &seen.transport(observer.port));
}

#[test]
fn the_delegate_transport_matches_its_committed_capture() {
    let observer = HttpObserver::start(200, "", BASIC);
    let (_, seen) = observe(&observer, Some(&delegate_program()));
    assert_capture("delegate_http_head.txt", &seen.transport(observer.port));
}

/// Drive `bz` at an `https://127.0.0.1:port` that never answers the handshake, and
/// hand back its exit code — the first flight lands in the observer's channel.
fn provoke_client_hello(port: u16) -> i32 {
    let cfg = config(&format!("https://127.0.0.1:{port}"), None);
    let args: Vec<String> = [
        "--config",
        cfg.to_str().expect("config path"),
        "--provider",
        "obs",
        "--model",
        "claude-x",
        "--api-key",
        "sk",
        "hi",
    ]
    .iter()
    .map(|s| (*s).to_owned())
    .collect();
    exec::run_bz(&args, "").0
}

#[test]
fn the_built_in_tls_client_hello_matches_its_committed_capture() {
    // Instrument B (spec §8.2): no certificate and no TLS server — the ClientHello
    // IS the fingerprint, so reading the first flight and hanging up suffices. The
    // run then fails, which is itself the documented transport-failure exit.
    let (port, hellos) = transport_support::clienthello_observer();
    assert_eq!(
        provoke_client_hello(port),
        69,
        "a dropped TLS handshake is a transport failure"
    );
    let flight = hellos
        .recv_timeout(std::time::Duration::from_secs(20))
        .expect("no TLS first flight reached the observer");
    let print = fingerprint(&flight).expect("not a ClientHello");
    assert_capture("builtin_clienthello.txt", &print.to_capture());
}

#[test]
fn the_built_in_client_hello_is_not_even_stable_connection_to_connection() {
    // Evidence for spec §2.3, not a lament: rustls deliberately SHUFFLES its
    // ClientHello extension order per connection, so brazen's shipped stack has no
    // fixed fingerprint to match against ANY reference client — configuration cannot
    // make it wire-identical to one, which is precisely why the seam exists. The
    // committed capture therefore pins the sorted OFFER, never the permutation.
    let (port, hellos) = transport_support::clienthello_observer();
    let mut seen = std::collections::BTreeSet::new();
    let mut offers = std::collections::BTreeSet::new();
    for _ in 0..5 {
        assert_eq!(provoke_client_hello(port), 69);
        let flight = hellos
            .recv_timeout(std::time::Duration::from_secs(20))
            .expect("no TLS first flight reached the observer");
        let print = fingerprint(&flight).expect("not a ClientHello");
        seen.insert(print.ja3());
        offers.insert(print.to_capture());
    }
    assert!(
        seen.len() > 1,
        "five connections produced one JA3 — the shuffle claim needs re-checking: {seen:?}"
    );
    assert_eq!(
        offers.len(),
        1,
        "the sorted OFFER must be stable: {offers:?}"
    );
}

#[test]
fn the_fingerprint_instrument_discriminates_between_stacks() {
    // The instrument must measure the thing, not a constant: a ClientHello captured
    // from a DIFFERENT stack (provenance in the fixture's sidecar) must fingerprint
    // differently from ours. Without this, the pin above could be vacuous.
    let foreign = std::fs::read(fixture("foreign_clienthello.bin")).expect("foreign capture");
    let theirs = fingerprint(&foreign).expect("not a ClientHello");
    let ours = std::fs::read_to_string(fixture("builtin_clienthello.txt")).expect("our capture");
    assert_ne!(theirs.to_capture(), ours);
    assert!(
        !theirs.ja3().is_empty() && !theirs.alpn.is_empty(),
        "{theirs:?}"
    );
}

fn fixture(name: &str) -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/transport")
        .join(name)
}

/// Compare an observation against its committed capture. `BZ_CAPTURE=1` rewrites the
/// fixture instead of asserting — how a capture is (re)taken, so the reference is
/// always a real observation and never hand-authored.
fn assert_capture(name: &str, observed: &str) {
    let path = fixture(name);
    if std::env::var_os("BZ_CAPTURE").is_some() {
        std::fs::write(&path, observed).expect("write capture");
        return;
    }
    let expected = std::fs::read_to_string(&path).expect("committed capture");
    assert_eq!(
        observed.trim(),
        expected.trim(),
        "{name} drifted; re-capture with BZ_CAPTURE=1 and review the diff"
    );
}
